### ISSUE TITLE
Bug with the wooden utensils photos 

### ISSUE THREAD

**Issue by artemis-toumazi** [oorestisime/kayon-decor#44]
There is an error in the photos of the wooden utensils. We changed them but there are still the old photos on the website. 
Please fix it!

**Comment by KostasTheodoro** [comment]
it might not have been pushed for some reason will check

**Comment by KostasTheodoro** [comment]
@oorestisime this reverted with the script and change of all photos to jpg. so basically we now have both photos in the file the old and the new but the old are rendering cause the others are not jpg. Since you builded the script etc etc and fixed the images, do you want to handle it or tell me how you want me to proceed?

**Comment by oorestisime** [comment]
I ll take care of it cousin
